//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calisanlar
    {
        public int Calisan_id { get; set; }
        public string Calisan_ad { get; set; }
        public string Calisan_soyad { get; set; }
        public string Calisan_sifre { get; set; }
        public string Calisan_telefon { get; set; }
        public string Calisan_adres { get; set; }
        public string Calisan_eposta { get; set; }
        public string Unvan { get; set; }
        public int Kutuphane_id { get; set; }
        public string Nobet_gunleri { get; set; }
    
        public virtual Kutuphane Kutuphane { get; set; }
    }
}
