//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitap_Yayinevi
    {
        public int Kitap_id { get; set; }
        public int Yayinevi_id { get; set; }
        public Nullable<int> Basim_tarihi { get; set; }
        public int Kayit_no { get; set; }
    
        public virtual Kitap Kitap { get; set; }
        public virtual Yayinevi Yayinevi { get; set; }
    }
}
