//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kutuphane_Uye
    {
        public int Kutuphane_id { get; set; }
        public int Uye_id { get; set; }
        public int Kayit_id { get; set; }
    
        public virtual Kutuphane Kutuphane { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
