//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yayinevi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yayinevi()
        {
            this.Kitap_Yayinevi = new HashSet<Kitap_Yayinevi>();
        }
    
        public int Yayinevi_id { get; set; }
        public string Yayinevi_ad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kitap_Yayinevi> Kitap_Yayinevi { get; set; }
    }
}
